name    'lboynton-ejabberd'
version '0.0.5'
source 'https://github.com/lboynton/puppet-ejabberd'
author 'lboynton'
license 'Apache License, Version 2.0'
summary 'Installs and configures ejabberd on CentOS'
description 'Installs and configures ejabberd on CentOS'
project_page 'https://github.com/lboynton/puppet-ejabberd'

dependency 'puppetlabs/vcsrepo', '0.2.x'
dependency 'stahnma/epel', '0.0.x'
